import baseWorker from "./index.js";
import {buildPushPayload} from "@block65/webcrypto-web-push";

const STATE_KEY="weather_state_v1",SUB_PREFIX="push_subscription_v1:",TIMEZONE="Asia/Seoul",STALE_MS=75*60*1000,RACE_DATE="2026-10-18",SEARCH_DAYS=7;
const SUWON={latitude:37.2636,longitude:127.0286};
const THUNDER_CODES=new Set([95,96,99]),STRONG_RAIN_CODES=new Set([65,67,82]);
const RUN_INDEX_MOVE_BELOW=40,RUN_INDEX_NORMAL_MIN=60,RUN_DAY_START_HOUR=5,RUN_DAY_END_HOUR=22;
const workouts=[
  ["2026-09-01","easy","Easy 3.5~4km"],["2026-09-04","easy","Easy 4km"],["2026-09-07","long","Long Easy 5km"],["2026-09-09","easy","Easy 4.5km"],["2026-09-11","quality","4분 지속주 × 4"],["2026-09-14","long","Long Easy 6km"],["2026-09-16","easy","Easy 5km"],["2026-09-18","quality","1.5km Tempo × 2"],["2026-09-21","long","Long Easy 7km"],["2026-09-23","easy","Easy 5km"],["2026-09-25","quality","1km × 3"],["2026-09-28","long","Long Easy 8km"],["2026-09-30","easy","Easy 4km"],["2026-10-02","quality","⭐ 5km 기록 테스트"],["2026-10-05","long","Long Easy 8.5~9km"],["2026-10-07","easy","Easy 4~5km"],["2026-10-09","quality","⭐ Goal Pace 1km × 4"],["2026-10-12","easy","Easy 6km"],["2026-10-13","easy","Easy 4km + Strides"],["2026-10-14","rest","휴식"],["2026-10-15","quality","Race Pace 자극"],["2026-10-16","rest","완전 휴식"],["2026-10-17","rest","대회 전날"],["2026-10-18","race","🏁 STYLE RUN 10K"]
].map(([date,type,title])=>({date,type,title}));

function allowedOrigin(env,request){const origin=request.headers.get("Origin")||"",configured=env.ALLOWED_ORIGIN||"https://dev-sjyong.github.io";return origin===configured?origin:configured}
function corsHeaders(env,request){return{"Access-Control-Allow-Origin":allowedOrigin(env,request),"Access-Control-Allow-Methods":"GET, POST, DELETE, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Cache-Control":"no-store","Vary":"Origin"}}
function json(data,status,env,request){return new Response(JSON.stringify(data,null,2),{status,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders(env,request)}})}
function kstParts(date=new Date()){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date),v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return{date:`${v.year}-${v.month}-${v.day}`,hour:Number(v.hour),minute:Number(v.minute),second:Number(v.second),text:`${v.year}-${v.month}-${v.day}T${v.hour}:${v.minute}:${v.second}+09:00`}}
function nextWholeHourKey(now=kstParts()){if(now.minute===0&&now.second===0)return`${now.date}T${String(now.hour).padStart(2,"0")}:00`;const d=new Date(`${now.date}T${String(now.hour).padStart(2,"0")}:00:00+09:00`);d.setTime(d.getTime()+3600000);const next=kstParts(d);return`${next.date}T${String(next.hour).padStart(2,"0")}:00`}
function parseDate(date){return new Date(`${date}T12:00:00+09:00`)}
function dateAdd(date,days){const d=parseDate(date);d.setDate(d.getDate()+days);return new Intl.DateTimeFormat("en-CA",{timeZone:TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function dayDiff(from,to){return Math.round((parseDate(to)-parseDate(from))/86400000)}
function addHours(local,hours){const d=new Date(`${local}:00+09:00`);d.setTime(d.getTime()+hours*3600000);const p=kstParts(d);return`${p.date}T${String(p.hour).padStart(2,"0")}:00`}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function isUnsafeHour(h){return THUNDER_CODES.has(h.code)||STRONG_RAIN_CODES.has(h.code)||h.precipitationProbability>=70||h.precipitation>=0.5}

function runningIndexScore(row){let score=100;const feels=Number.isFinite(row.apparent)?row.apparent:row.temperature,humidity=row.humidity,rainChance=row.precipitationProbability||0,rain=row.precipitation||0,wind=row.wind||0;if(feels<-5)score-=45;else if(feels<0)score-=30;else if(feels<5)score-=12;else if(feels<=18)score-=0;else if(feels<=22)score-=(feels-18)*1.5;else if(feels<=26)score-=6+(feels-22)*3;else if(feels<=30)score-=18+(feels-26)*5;else score-=38+(feels-30)*7;if(Number.isFinite(humidity)&&feels>=18&&humidity>65)score-=Math.min(18,(humidity-65)*0.55);if(rainChance>20)score-=Math.min(28,(rainChance-20)*0.45);if(rain>=3)score-=60;else if(rain>=1)score-=42;else if(rain>=0.5)score-=28;else if(rain>=0.1)score-=12;if(wind>15)score-=Math.min(32,(wind-15)*1.1);if(THUNDER_CODES.has(row.code))score=Math.min(score,5);else if(STRONG_RAIN_CODES.has(row.code))score=Math.min(score,18);return Math.round(clamp(score,0,100))}
function compactHour(data,i){const row={time:data.hourly.time[i],code:data.hourly.weather_code[i],temperature:data.hourly.temperature_2m[i],apparent:data.hourly.apparent_temperature?.[i]??data.hourly.temperature_2m[i],humidity:data.hourly.relative_humidity_2m?.[i]??null,precipitationProbability:data.hourly.precipitation_probability[i]??0,precipitation:data.hourly.precipitation[i]??0,wind:data.hourly.wind_speed_10m[i]??0};return{...row,runningIndex:runningIndexScore(row)}}
function bestWindow(hours,required,minScore){let best=null;for(let i=0;i<=hours.length-required;i++){const slice=hours.slice(i,i+required);if(!slice.every((p,j)=>{const prev=j?slice[j-1]:null;return(!prev||p.time===addHours(prev.time,1))&&!isUnsafeHour(p)&&p.runningIndex>=minScore}))continue;const score=Math.round(slice.reduce((s,p)=>s+p.runningIndex,0)/slice.length);if(!best||score>best.score)best={start:slice[0].time,end:addHours(slice[slice.length-1].time,1),hours:required,score,rows:slice}}return best}
function bestAnyWindow(hours,required){let best=null;for(let i=0;i<=hours.length-required;i++){const slice=hours.slice(i,i+required);if(!slice.every((p,j)=>!j||p.time===addHours(slice[j-1].time,1)))continue;const score=Math.round(slice.reduce((s,p)=>s+p.runningIndex,0)/slice.length);if(!best||score>best.score)best={start:slice[0].time,end:addHours(slice[slice.length-1].time,1),hours:required,score,rows:slice}}return best}
function assessRunWindows(hours,required){const normal=bestWindow(hours,required,RUN_INDEX_NORMAL_MIN);if(normal)return{canRun:true,mode:"normal",bestScore:normal.score,safeWindow:normal,advice:"정상 훈련 가능"};const reduced=bestWindow(hours,required,RUN_INDEX_MOVE_BELOW);if(reduced)return{canRun:true,mode:"reduced",bestScore:reduced.score,safeWindow:reduced,advice:"거리 10~20% 단축 · 목표 페이스 15~30초/km 완화 · RPE 우선"};const best=bestAnyWindow(hours,required);return{canRun:false,mode:"move",bestScore:best?.score??null,safeWindow:null,bestWindow:best,advice:"오늘 남은 적정 러닝 구간이 없어 자동 이동 대상"}}
function hoursByDate(data){const map={};data.hourly.time.forEach((time,i)=>{const hour=Number(time.slice(11,13));if(hour<RUN_DAY_START_HOUR||hour>=RUN_DAY_END_HOUR)return;const date=time.slice(0,10);(map[date]??=[]).push(compactHour(data,i))});return map}
function runningIndexMap(data){const result={};for(const[date,hours]of Object.entries(hoursByDate(data)))result[date]={easy:assessRunWindows(hours,1),hard:assessRunWindows(hours,2)};return result}
async function fetchIndexForecast(){const params=new URLSearchParams({latitude:String(SUWON.latitude),longitude:String(SUWON.longitude),timezone:TIMEZONE,forecast_days:"16",hourly:["weather_code","temperature_2m","apparent_temperature","relative_humidity_2m","precipitation_probability","precipitation","wind_speed_10m"].join(",")}),r=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!r.ok)throw new Error(`Running index Open-Meteo error: ${r.status}`);return r.json()}
function enrichState(raw,indexData){const generatedAt=new Date(raw.generatedAt||Date.now()),now=kstParts(generatedAt),from=nextWholeHourKey(now),all=indexData.hourly.time.map((_,i)=>compactHour(indexData,i)),remaining=all.filter(h=>h.time.startsWith(`${now.date}T`)&&h.time>=from&&Number(h.time.slice(11,13))<RUN_DAY_END_HOUR),easy=assessRunWindows(remaining,1),hard=assessRunWindows(remaining,2);return{...raw,version:2,today:{...(raw.today||{}),date:now.date,assessedAt:now.text,assessmentFrom:from,rules:{...(raw.today?.rules||{}),runIndexMoveBelow:RUN_INDEX_MOVE_BELOW,runIndexNormalMin:RUN_INDEX_NORMAL_MIN,runDayEndHour:RUN_DAY_END_HOUR},easy,hard,runningIndex:{easy,hard},remainingHours:remaining},suwonRunIndex:runningIndexMap(indexData)}}
async function readState(env){return env.WEATHER_STATE?.get(STATE_KEY,"json")||null}
function isStale(state){return state?.version!==2||!state?.generatedAt||Date.now()-new Date(state.generatedAt).getTime()>STALE_MS}
function mutedEnv(env){return Object.assign(Object.create(env),{VAPID_PUBLIC_KEY:"",VAPID_PRIVATE_KEY:""})}
async function rebuildState(env){const req=new Request("https://internal.invalid/api/weather?refresh=1",{method:"GET"}),rawResponse=await baseWorker.fetch(req,mutedEnv(env));if(!rawResponse.ok)throw new Error(`Base weather refresh failed: ${rawResponse.status}`);const raw=await rawResponse.json(),indexData=await fetchIndexForecast(),state=enrichState(raw,indexData);await env.WEATHER_STATE.put(STATE_KEY,JSON.stringify(state));return state}

function isRunning(w){return["easy","long","quality"].includes(w.type)}
function isHard(w){return["long","quality"].includes(w.type)}
function minGap(a,b){return(["quality","long"].includes(a)||["quality","long"].includes(b))?2:1}
function runIndexAssessment(state,w,date){const key=w.type==="easy"?"easy":"hard";if(date===state?.today?.date)return state.today.runningIndex?.[key]||state.today?.[key]||null;return state?.suwonRunIndex?.[date]?.[key]||null}
function weatherBad(state,w,date){const idx=runIndexAssessment(state,w,date);if(idx)return idx.canRun===false||idx.mode==="move";const d=state?.suwonDaily?.[date];return Boolean(d&&(THUNDER_CODES.has(d.code)||STRONG_RAIN_CODES.has(d.code)||d.precipitation>=70))}
function weatherPenalty(state,w,date){const idx=runIndexAssessment(state,w,date);let s=0;if(idx){if(idx.mode==="reduced")s+=18;else if(idx.mode==="normal"&&Number.isFinite(idx.bestScore))s+=Math.max(0,(80-idx.bestScore)/5)}const d=state?.suwonDaily?.[date];if(!d)return s;if(d.precipitation>=40)s+=18;else if(d.precipitation>=20)s+=6;if(d.wind>=30)s+=12;if(d.max>=30)s+=10;else if(d.max>=28)s+=5;return s}
function normalizeUser(v={}){return{autoEnabled:v.autoEnabled!==false,done:v.done&&typeof v.done==="object"?v.done:{},locked:v.locked&&typeof v.locked==="object"?v.locked:{},lockDates:v.lockDates&&typeof v.lockDates==="object"?v.lockDates:{},actualDates:v.actualDates&&typeof v.actualDates==="object"?v.actualDates:{},defers:v.defers&&typeof v.defers==="object"?v.defers:{}}}
function adaptiveSchedule(state,value={}){const user=normalizeUser(value),today=state?.today?.date||kstParts().date,taper=dateAdd(RACE_DATE,-2),entries=workouts.map(w=>({...w,effectiveDate:w.date})),rest=new Set(workouts.filter(w=>w.type==="rest").map(w=>w.date)),occupied=new Map();let previous=null;const nextAnchor=i=>{for(let j=i+1;j<entries.length;j++){const n=entries[j];if(n.type==="race")return{date:n.date,type:n.type,fixed:true};if(user.done[n.date])return{date:user.actualDates[n.date]||n.date,type:n.type,fixed:true};if(user.locked[n.date])return{date:user.lockDates[n.date]||n.date,type:n.type,fixed:true};if(isHard(n))return{date:n.date,type:n.type,fixed:false}}return{date:RACE_DATE,type:"race",fixed:true}};for(let i=0;i<entries.length;i++){const w=entries[i];if(w.type==="race"){occupied.set(w.date,w.date);previous={date:w.date,type:w.type};continue}if(!isRunning(w))continue;if(user.done[w.date]){w.effectiveDate=user.actualDates[w.date]||w.date;occupied.set(w.effectiveDate,w.date);previous={date:w.effectiveDate,type:w.type};continue}if(user.locked[w.date]){w.effectiveDate=user.lockDates[w.date]||w.date;occupied.set(w.effectiveDate,w.date);previous={date:w.effectiveDate,type:w.type};continue}const manual=user.defers[w.date],triggered=user.autoEnabled&&weatherBad(state,w,w.date),past=dayDiff(w.date,today)>0;if(past&&!manual&&!triggered){occupied.set(w.date,w.date);previous={date:w.date,type:w.type};continue}let start=w.date;if(manual?.notBefore>start)start=manual.notBefore;if(previous){const earliest=dateAdd(previous.date,minGap(previous.type,w.type));if(earliest>start)start=earliest}if(start>=taper&&w.date<taper)continue;const anchor=nextAnchor(i);let best=null,bestScore=Infinity;for(let offset=0;offset<=SEARCH_DAYS;offset++){const candidate=dateAdd(start,offset);if(candidate>=RACE_DATE||candidate>=taper)break;if(occupied.has(candidate)||rest.has(candidate)||(user.autoEnabled&&weatherBad(state,w,candidate)))continue;if(previous&&dayDiff(previous.date,candidate)<minGap(previous.type,w.type))continue;const idx=runIndexAssessment(state,w,candidate),weatherCost=candidate===w.date&&idx?.mode==="reduced"?0:weatherPenalty(state,w,candidate);let score=dayDiff(start,candidate)*10+Math.max(0,dayDiff(w.date,candidate))*2+weatherCost,gap=dayDiff(candidate,anchor.date),need=minGap(w.type,anchor.type);if(gap<need)score+=anchor.fixed?10000:600;else if(gap===need)score+=10;else if(gap===need+1)score+=2;if(score<bestScore){best=candidate;bestScore=score}}if(!best)continue;w.effectiveDate=best;occupied.set(best,w.date);previous={date:best,type:w.type}}return entries.filter(isRunning)}
function scheduleChanges(oldState,newState,userState){if(!oldState||!newState||userState?.autoEnabled===false)return[];const before=new Map(adaptiveSchedule(oldState,userState).map(w=>[w.date,w]));return adaptiveSchedule(newState,userState).flatMap(after=>{const old=before.get(after.date);if(!old||old.effectiveDate===after.effectiveDate)return[];return[{action:after.effectiveDate===after.date?"복귀":"이동",title:after.title,baseDate:after.date,from:old.effectiveDate,to:after.effectiveDate}]})}
function monthDay(date){const[,m,d]=date.split("-");return`${Number(m)}/${Number(d)}`}
function pushMessage(changes){const first=changes[0],more=changes.length>1?` 외 ${changes.length-1}건`:"";return{title:`🏃 훈련 일정 ${first.action}`,body:`${first.title}: ${monthDay(first.from)} → ${monthDay(first.to)}${more}`,url:"./",tag:"run10k-weather-schedule",changes}}
async function listSubscriptions(env){const records=[];let cursor;do{const page=await env.WEATHER_STATE.list({prefix:SUB_PREFIX,cursor});for(const item of page.keys){const record=await env.WEATHER_STATE.get(item.name,"json");if(record)records.push({key:item.name,record})}cursor=page.list_complete?undefined:page.cursor}while(cursor);return records}
async function sendPush(env,subscription,message){if(!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_KEY)throw new Error("VAPID secrets are not configured");const payload=await buildPushPayload({data:JSON.stringify(message),options:{ttl:3600,urgency:"normal",topic:"run10k-schedule"}},subscription,{subject:env.VAPID_SUBJECT||"https://dev-sjyong.github.io/10km-run/",publicKey:env.VAPID_PUBLIC_KEY,privateKey:env.VAPID_PRIVATE_KEY});return fetch(subscription.endpoint,payload)}
async function notifyChanges(env,oldState,newState){if(!oldState||!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_KEY)return;const records=await listSubscriptions(env);await Promise.all(records.map(async({key,record})=>{const changes=scheduleChanges(oldState,newState,record.userState);if(!changes.length)return;try{const response=await sendPush(env,record.subscription,pushMessage(changes));if(response.status===404||response.status===410)await env.WEATHER_STATE.delete(key);else if(!response.ok)console.error("Push rejected",response.status)}catch(error){console.error("Push failed",error)}}))}
async function refreshAndNotify(env){const oldState=await readState(env),newState=await rebuildState(env);await notifyChanges(env,oldState,newState);return newState}

export default{
  async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(env,request)});const url=new URL(request.url);if(url.pathname==="/api/weather"&&request.method==="GET"){try{const force=url.searchParams.get("refresh")==="1";let state=force?await refreshAndNotify(env):await readState(env);if(!force&&isStale(state))state=await refreshAndNotify(env);return json(state,200,env,request)}catch(error){return json({error:"Weather state unavailable",message:error instanceof Error?error.message:String(error)},503,env,request)}}if(url.pathname==="/api/health"&&request.method==="GET"){const state=await readState(env);return json({ok:true,service:"10km-run-weather-scheduler-v2",hasState:Boolean(state),stateGeneratedAt:state?.generatedAt||null,stateVersion:state?.version||null,stale:isStale(state),pushConfigured:Boolean(env.VAPID_PUBLIC_KEY&&env.VAPID_PRIVATE_KEY),runningIndex:{moveBelow:RUN_INDEX_MOVE_BELOW,normalMin:RUN_INDEX_NORMAL_MIN}},200,env,request)}return baseWorker.fetch(request,env)},
  async scheduled(_controller,env,ctx){ctx.waitUntil(refreshAndNotify(env).catch(error=>console.error("Scheduled weather/index refresh failed",error)))}
};

export{adaptiveSchedule,scheduleChanges,runningIndexScore,assessRunWindows};
